version: '3.6'
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_DOMAIN: "univ-ville.fr"
    command: --copy-service
    volumes:
     - ./docker4dev/ldap-config/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
     - ./docker4dev/ldap-config/schema:/container/service/slapd/assets/config/bootstrap/schema/custom
    ports:
     - 3890:389
  cas:
    image: esupportail/apereo-cas-ldap:v6.6.0
    container_name: cas
    volumes:
      - ./docker4dev/cas-config:/etc/cas
      - ./docker4dev/cas-config/tmp-cas:/tmp/cas
    ports:
      - "8081:8080"
    depends_on:
      - openldap     
  mariadb:
    image: "mariadb:10.3"
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=esup
      - MYSQL_USER=entng
      - MYSQL_PASSWORD=esup
      - MYSQL_DATABASE=entng
    ports:
      - 3306:3306
  backend:
    build: portillon-backend
    command: "mvn spring-boot:run"
    ports:
      - 8080:8080
    depends_on:
      - mariadb      
  frontend:
    build: portillon-frontend
    command: "ng serve --host 0.0.0.0 --aot=true"
    ports:
      - 4200:4200

